CREATE TABLE IF NOT EXISTS file_entry (
    id SERIAL PRIMARY KEY,
    scan_id INTEGER REFERENCES scan(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name CHARACTER VARYING NOT NULL,
    size BIGINT NOT NULL,
    mode BIGINT NOT NULL,
    mod_time TIMESTAMP WITH TIME ZONE NOT NULL,
    is_dir BOOLEAN NOT NULL,
    hash VARCHAR(32) NOT NULL,
    error CHARACTER VARYING
);