CREATE TABLE IF NOT EXISTS scan (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    hostname CHARACTER VARYING NOT NULL,
    root_directory CHARACTER VARYING NOT NULL,
    files_scanned INTEGER,
    scan_status CHARACTER VARYING NOT NULL
);